### ISSUE TITLE
Thumbnail be Broken if there are two line of title

### ISSUE THREAD

**Issue by alfathony** [wuriyanto48/wuriyanto48.github.io#5]
![image](https://user-images.githubusercontent.com/14884603/66946493-3f96c580-f07b-11e9-86c7-fc2cfba9308f.png)
 
I suggested using a _masonry card view_ with upgrade the framework bootstrap to the latest version.

I am honored to be able to do this

**Comment by wuriyanto48** [comment]
@alfathony , can you help me?
just send me a Pull Request :D

**Comment by wuriyanto48** [comment]
also, add your github link to https://github.com/wuriyanto48/wuriyanto48.github.io/blob/master/Thanks.md

thank you
