### ISSUE TITLE
Missing Gemfile and how-to in documentation

### ISSUE THREAD

**Issue by azhsetiawan** [wuriyanto48/wuriyanto48.github.io#6]
Hi @wuriyanto48 

`Gemfile` is not included in your repository. It's easier for someone to contribute if you provide `Gemfile` and step by step how to run jekyll local development in your `README.md`.

Just give my simple opinion, hope it helps make your repository become better

Maturnuwun

**Comment by wuriyanto48** [comment]
hmm would be cool,, i will consider it

**Comment by wuriyanto48** [comment]
https://github.com/wuriyanto48/wuriyanto48.github.io/commit/62e745e7407628e4e7cf489763ccbf5e2e5d6530
